install:
	$(MAKE) --directory=./src -f Makefile.old install

cleaninstall:
	$(MAKE) --directory=./src -f Makefile.old cleaninstall

clean:
	$(MAKE) --directory=./src -f Makefile.old clean

release:
	$(MAKE) --directory=./src -f Makefile.old release

cleansettings :
	rm -rf /boot/home/config/settings/Hare/$(NAME)
