install:
	$(MAKE) --directory=./AEEncoder install
	$(MAKE) --directory=./BeEncoder install
	$(MAKE) --directory=./MP3GoGo install
	$(MAKE) --directory=./MP3Lame install
	$(MAKE) --directory=./OGGEncoder install
	$(MAKE) --directory=./M3UCreator install
	$(MAKE) --directory=./Hare install

cleaninstall:
	$(MAKE) --directory=./AEEncoder cleaninstall
	$(MAKE) --directory=./BeEncoder cleaninstall
	$(MAKE) --directory=./MP3GoGo cleaninstall
	$(MAKE) --directory=./MP3Lame cleaninstall
	$(MAKE) --directory=./OGGEncoder cleaninstall
	$(MAKE) --directory=./M3UCreator cleaninstall
	$(MAKE) --directory=./Hare cleaninstall

clean:
	$(MAKE) --directory=./AEEncoder clean
	$(MAKE) --directory=./BeEncoder clean
	$(MAKE) --directory=./MP3GoGo clean
	$(MAKE) --directory=./MP3Lame clean
	$(MAKE) --directory=./OGGEncoder clean
	$(MAKE) --directory=./M3UCreator clean
	$(MAKE) --directory=./Hare clean

release:
	$(MAKE) --directory=./AEEncoder release
	$(MAKE) --directory=./BeEncoder release
	$(MAKE) --directory=./MP3GoGo release
	$(MAKE) --directory=./MP3Lame release
	$(MAKE) --directory=./OGGEncoder release
	$(MAKE) --directory=./M3UCreator release
	$(MAKE) --directory=./Hare release

cleansettings :
	rm -rf /boot/home/config/settings/Hare/$(NAME)
