install:
	$(MAKE) --directory=./AEEncoder install
	$(MAKE) --directory=./FlipSideAE install
	$(MAKE) --directory=./BeEncoder install
	$(MAKE) --directory=./MP3GoGo install
	$(MAKE) --directory=./MP3Lame install
	$(MAKE) --directory=./OGGEncoder install
	$(MAKE) --directory=./M3UCreator install

cleaninstall:
	$(MAKE) --directory=./AEEncoder cleaninstall
	$(MAKE) --directory=./FlipSideAE cleaninstall
	$(MAKE) --directory=./BeEncoder cleaninstall
	$(MAKE) --directory=./MP3GoGo cleaninstall
	$(MAKE) --directory=./MP3Lame cleaninstall
	$(MAKE) --directory=./OGGEncoder cleaninstall
	$(MAKE) --directory=./M3UCreator cleaninstall

clean:
	$(MAKE) --directory=./AEEncoder clean
	$(MAKE) --directory=./FlipSideAE clean
	$(MAKE) --directory=./BeEncoder clean
	$(MAKE) --directory=./MP3GoGo clean
	$(MAKE) --directory=./MP3Lame clean
	$(MAKE) --directory=./OGGEncoder clean
	$(MAKE) --directory=./M3UCreator clean

release:
	$(MAKE) --directory=./AEEncoder release
	$(MAKE) --directory=./FlipSideAE release
	$(MAKE) --directory=./BeEncoder release
	$(MAKE) --directory=./MP3GoGo release
	$(MAKE) --directory=./MP3Lame release
	$(MAKE) --directory=./OGGEncoder release
	$(MAKE) --directory=./M3UCreator release

cleansettings :
	rm -rf /boot/home/config/settings/FlipSide\ Software/$(NAME)
