all:
	$(MAKE) --directory=./String/ install
	$(MAKE) --directory=./Matcher/ install
	$(MAKE) --directory=./Santa/ install

install:
	$(MAKE) --directory=./String/ install
	$(MAKE) --directory=./Matcher/ install
	$(MAKE) --directory=./AudioInfo/ install
	$(MAKE) --directory=./Santa/ install
	$(MAKE) --directory=./Hare/ install

clean:
	$(MAKE) --directory=./String/ clean
	$(MAKE) --directory=./Matcher/ clean
	$(MAKE) --directory=./AudioInfo/ clean
	$(MAKE) --directory=./Santa/ clean
	$(MAKE) --directory=./Hare/ clean

release:
	$(MAKE) --directory=./String/ release
	$(MAKE) --directory=./Matcher/ release
	$(MAKE) --directory=./AudioInfo/ release
	$(MAKE) --directory=./Santa/ release
	$(MAKE) --directory=./Hare/ release

cleaninstall:
	$(MAKE) --directory=./String/ cleaninstall
	$(MAKE) --directory=./Matcher/ cleaninstall
	$(MAKE) --directory=./AudioInfo/ cleaninstall
	$(MAKE) --directory=./Santa/ cleaninstall
	$(MAKE) --directory=./Hare/ cleaninstall
